
void Durchschieben(){
  digitalWrite(ES, HIGH);
  delay(500);
  digitalWrite(IST, HIGH);
  delay(500);
  digitalWrite(WAR, HIGH);
  delay(500);
  digitalWrite(JETZT, HIGH);
  delay(500);
  digitalWrite(GLEICH, HIGH);
  delay(500);
  digitalWrite(ZEHN_1, HIGH);
  delay(500);
  digitalWrite(ZWANZIG, HIGH);
  delay(500);
  digitalWrite(VIERTEL, HIGH);
  delay(500);
  digitalWrite(HALB, HIGH);
  delay(500);
  digitalWrite(FUENF_1, HIGH);
  delay(500);
  digitalWrite(VOR, HIGH);
  delay(500);
  digitalWrite(NACH, HIGH);
  delay(500);
  digitalWrite(EIN, HIGH);
  delay(500);
  digitalWrite(S, HIGH);
  delay(500);
  digitalWrite(ZWEI, HIGH);
  delay(500);
  digitalWrite(DREI, HIGH);
  delay(500);
  digitalWrite(VIER, HIGH);
  delay(500);
  digitalWrite(FUENF_2, HIGH);
  delay(500);
  digitalWrite(SECHS, HIGH);
  delay(500);
  digitalWrite(SIEBEN, HIGH);
  delay(500);
  digitalWrite(ACHT, HIGH);
  delay(500);
  digitalWrite(NEUN, HIGH);
  delay(500);
  digitalWrite(ZEHN_2, HIGH);
  delay(500);
  digitalWrite(ELF, HIGH);
  delay(500);
  digitalWrite(ZWOELF, HIGH);
  delay(500);
  digitalWrite(UHR, HIGH);
  delay(500);
   Serial.println("Effekt 1 Abgeschlossen...");
  //------------------------------------------
  digitalWrite(ES, LOW);
  delay(500);
  digitalWrite(IST, LOW);
  delay(500);
  digitalWrite(WAR, LOW);
  delay(500);
  digitalWrite(JETZT, LOW);
  delay(500);
  digitalWrite(GLEICH, LOW);
  delay(500);
  digitalWrite(ZEHN_1, LOW);
  delay(500);
  digitalWrite(ZWANZIG, LOW);
  delay(500);
  digitalWrite(VIERTEL, LOW);
  delay(500);
  digitalWrite(HALB, LOW);
  delay(500);
  digitalWrite(FUENF_1, LOW);
  delay(500);
  digitalWrite(VOR, LOW);
  delay(500);
  digitalWrite(NACH, LOW);
  delay(500);
  digitalWrite(EIN, LOW);
  delay(500);
  digitalWrite(S, LOW);
  delay(500);
  digitalWrite(ZWEI, LOW);
  delay(500);
  digitalWrite(DREI, LOW);
  delay(500);
  digitalWrite(VIER, LOW);
  delay(500);
  digitalWrite(FUENF_2, LOW);
  delay(500);
  digitalWrite(SECHS, LOW);
  delay(500);
  digitalWrite(SIEBEN, LOW);
  delay(500);
  digitalWrite(ACHT, LOW);
  delay(500);
  digitalWrite(NEUN, LOW);
  delay(500);
  digitalWrite(ZEHN_2, LOW);
  delay(500);
  digitalWrite(ELF, LOW);
  delay(500);
  digitalWrite(ZWOELF, LOW);
  delay(500);
  digitalWrite(UHR, LOW);
}

void Blinken() {
  digitalWrite(ES, HIGH);
  delay(2);
  digitalWrite(IST, HIGH);
  delay(2);
  digitalWrite(WAR, HIGH);
  delay(2);
  digitalWrite(JETZT, HIGH);
  delay(2);
  digitalWrite(GLEICH, HIGH);
  delay(2);
  digitalWrite(ZEHN_1, HIGH);
  delay(2);
  digitalWrite(ZWANZIG, HIGH);
  delay(2);
  digitalWrite(VIERTEL, HIGH);
  delay(2);
  digitalWrite(HALB, HIGH);
  delay(2);
  digitalWrite(FUENF_1, HIGH);
  delay(2);
  digitalWrite(VOR, HIGH);
  delay(2);
  digitalWrite(NACH, HIGH);
  delay(2);
  digitalWrite(EIN, HIGH);
  delay(2);
  digitalWrite(S, HIGH);
  delay(2);
  digitalWrite(ZWEI, HIGH);
  delay(2);
  digitalWrite(DREI, HIGH);
  delay(2);
  digitalWrite(ES, HIGH);
  delay(2);
  digitalWrite(VIER, HIGH);
  delay(2);
  digitalWrite(FUENF_2, HIGH);
  delay(2);
  digitalWrite(SECHS, HIGH);
  delay(2);
  digitalWrite(SIEBEN, HIGH);
  delay(2);
  digitalWrite(ACHT, HIGH);
  delay(2);
  digitalWrite(NEUN, HIGH);
  delay(2);
  digitalWrite(ZEHN_2, HIGH);
  delay(2);
  digitalWrite(ELF, HIGH);
  delay(2);
  digitalWrite(ZWOELF, HIGH);
  delay(2);
  digitalWrite(UHR, HIGH);
  delay(500);
  digitalWrite(ES, LOW);
  delay(2);
  digitalWrite(IST, LOW);
  delay(2);
  digitalWrite(WAR, LOW);
  delay(2);
  digitalWrite(JETZT, LOW);
  delay(2);
  digitalWrite(GLEICH, LOW);
  delay(2);
  digitalWrite(ZEHN_1, LOW);
  delay(2);
  digitalWrite(ZWANZIG, LOW);
  delay(2);
  digitalWrite(VIERTEL, LOW);
  delay(2);
  digitalWrite(HALB, LOW);
  delay(2);
  digitalWrite(FUENF_1, LOW);
  delay(2);
  digitalWrite(VOR, LOW);
  delay(2);
  digitalWrite(NACH, LOW);
  delay(2);
  digitalWrite(EIN, LOW);
  delay(2);
  digitalWrite(S, LOW);
  delay(2);
  digitalWrite(ZWEI, LOW);
  delay(2);
  digitalWrite(DREI, LOW);
  delay(2);
  digitalWrite(ES, LOW);
  delay(2);
  digitalWrite(VIER, LOW);
  delay(2);
  digitalWrite(FUENF_2, LOW);
  delay(2);
  digitalWrite(SECHS, LOW);
  delay(2);
  digitalWrite(SIEBEN, LOW);
  delay(2);
  digitalWrite(ACHT, LOW);
  delay(2);
  digitalWrite(NEUN, LOW);
  delay(2);
  digitalWrite(ZEHN_2, LOW);
  delay(2);
  digitalWrite(ELF, LOW);
  delay(2);
  digitalWrite(ZWOELF, LOW);
  delay(2);
  digitalWrite(UHR, LOW);
  delay(500);
}


